---
- hosts: workstation
  become: true
  tasks:
    - name: Add Deadsnakes PPA with Python packages
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: Update apt-cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - jq
          - vim
          - git
          - curl
          - lm-sensors
          - python3.6
          - python3.7
          - python3.8
          - python3.9
          - python3-pip
          - python3-venv
          - python3-virtualenv
        state: latest

    - name: Disable sleep
      systemd:
        name: sleep.target
        masked: yes

    - name: Disable suspend
      systemd:
        name: suspend.target
        masked: yes

    - name: Disable hibernate.target
      systemd:
        name: hibernate.target
        masked: yes

    - name: Disable hybrid sleep
      systemd:
        name: hybrid-sleep.target
        masked: yes
