---
- hosts: workstation
  become: true
  roles:
    - role: nvidia.nvidia_driver
      vars:
        nvidia_driver_ubuntu_install_from_cuda_repo: yes
        nvidia_driver_ubuntu_branch: "460"
        nvidia_driver_ubuntu_packages: ["nvidia-headless-460-server", "nvidia-headless-460-utils"]
