---
- hosts: workstation
  become: true
  tasks:
    - name: Add Deadsnakes PPA with Python packages
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: Update apt-cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - jq
          - vim
          - git
          - curl
          - python3.6
          - python3.7
          - python3.8
          - python3.9
          - python3-pip
          - python3-virtualenv
        state: latest
