---
- hosts: workstation
  tasks:
    - name: Copy configuration file
      template:
        src: ../configs/vimrc.conf
        dest: ~/.vimrc
    
    - name: Prepare placeholder for Vundle
      file:
        path: ~/.vim/bundle/
        state: directory
        mode: "0755"

    - name: Clone Vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim

    - name: Install all plugins
      shell: vim +PluginInstall +qall
