---
- hosts: workstation
  become: true
  tasks:
    - name: Install Wireguard
      apt:
        name: wireguard

    - name: Generate keys
      shell: umask 077; wg genkey | tee server_privatekey | wg pubkey > server_publickey
      args:
        chdir: /etc/wireguard/

    - name: Generate keys
      shell: umask 077; wg genkey | tee client_privatekey | wg pubkey > client_publickey
      args:
        chdir: /etc/wireguard/

    - name: Read server private key
      command: cat /etc/wireguard/server_privatekey
      register: wireguard_server_privatekey

    - name: Read server public key
      command: cat /etc/wireguard/server_publickey
      register: wireguard_server_publickey

    - name: Read client private key
      command: cat /etc/wireguard/client_privatekey
      register: wireguard_client_privatekey

    - name: Read client public key
      command: cat /etc/wireguard/client_publickey
      register: wireguard_client_publickey

    - name: Copy configuration file and fill it with generated private key
      template:
        src: ../configs/wireguard_server.conf
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: 600

    - name: Create configuration file for client and fill it with generated public key
      become: false
      delegate_to: localhost
      template:
        src: ../configs/wireguard_client.conf
        dest: ../wireguard_client.conf

    - name: Allow for IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        reload: yes
        state: present

    - name: Allow for IPv6 forwarding
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        reload: yes
        state: present

    - name: Allow incoming traffic to VPN port
      ufw:
        rule: allow
        port: 51820
        proto: udp

    - name: Apply changes traffic to VPN 
      ufw:
        state: enabled

    - name: Enable Wireguard service
      service:
        name: wg-quick@wg0
        enabled: yes
        state: restarted
