---
- hosts: workstation
  tasks:
    - name: Install ZSH
      become: true
      apt:
        name: zsh

    - name: Get user name
      command: whoami
      register: whoami

    - name: Change default shell to ZSH
      become: true
      shell: "chsh -s /usr/bin/zsh {{ whoami.stdout }}"

    - name: Prepare placeholder for Oh-My-ZSH scripts
      file:
        path: /tmp/zsh
        state: directory
        mode: "0755"

    - name: Download Oh-My-ZSH installation script
      get_url:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/zsh/install.sh
        mode: "0755"
        force: yes

    - name: Make sure that there is nothing from previous installation
      file:
        path: ~/.oh-my-zsh
        state: absent

    - name: Install Oh-My-ZSH
      shell: /tmp/zsh/install.sh --unattended

    - name: Copy configuration file
      template:
        src: ../configs/zshrc.conf
        dest: ~/.zshrc
